#spring.application.name=QueryDsl_Springboot
server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: springboot_QueryDsl
  datasource:
    url: jdbc:sqlserver://localhost:57134;encrypt=true;trustServerCertificate=true;databaseName=rsql_QueryDsl
    username: admin
    password: admin
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE